-- create tables

create table project (
    id       number generated by default on null as identity
             constraint project_id_pk primary key,
    year     number(4) not null,
    name     varchar2(500 char) not null
);


create table tasks (
    id            number generated by default on null as identity
                  constraint tasks_id_pk primary key,
    project_id    number                  constraint tasks_project_id_fk
                  references project on delete cascade,
    orden         number(10) not null,
    name          varchar2(2000 char) not null,
    optimistic    number(10,2) not null,
    likely        number(10,2) not null,
    pesimistic    number(10,2) not null,
    enabled       number(1) default 0 not null
);

-- table index
create index tasks_i1 on tasks (project_id);

create table simulations (
    id            number generated by default on null as identity
                  constraint simulations_id_pk primary key,
    project_id    number                  constraint simulations_project_id_fk
                  references project on delete cascade,
    total         number(12,2) not null
);

create index simulations_i1 on simulations (project_id);

create table tasks_simulations (
    id            number generated by default on null as identity
                  constraint tsimulations_id_pk primary key,
    task_id    number                  constraint tsimulations_task_id_fk
                  references tasks on delete cascade,
    total         number(12,2) not null
);

create index tsimulations_i1 on tasks_simulations (task_id);

-- Generated by Quick SQL 1.2.9 8/11/2024, 19:26:25

/*
project
    year num(4) /nn
    name vc50 /nn
    total num(12,2)

    tasks
        name vc2000 /nn
        optimistic num(10,2) /nn
        likely num(10,2) /nn
        pesimistic num(10,2) /nn

 Non-default options:
# settings = {"apex":"Y","db":"19c","pk":"IDENTITY"}

*/